name: The Quantum Dojo
favicon: null
layout_spectrum: 0.99902
typography_spectrum: 0.25098
title: Conscious Leadership Evolution - Rebel Against Mediocrity
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#9f9f9f'
    - '#606060'
    - '#dd4240'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
