name: The Quantum Dojo
favicon: null
layout_spectrum: 1
typography_spectrum: 0.25588
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#f9d285'
    - '#ac4113'
    - '#df7b25'
    - '#fffcf7'
  brandStrength: 0.25
  lightness: 0.0625
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
